from enum import Enum


class ProgressStage(Enum):
    PREPARING = "preparing"
    REPAIRING_INSTANCE = "repairing_instance"
    SCANNING_REPAIR = "scanning_repair"
    VERIFYING_REPAIR = "verifying_repair"
    PLANNING_REPAIR = "planning_repair"
    APPLYING_REPAIR = "applying_repair"
    IMPORTING_INSTANCE = "importing_instance"
    EXPORTING_INSTANCE = "exporting_instance"
    LOADING_VERSION = "loading_version"
    DOWNLOADING_MOD_LOADER = "downloading_mod_loader"
    INSTALLING_MOD_LOADER = "installing_mod_loader"
    SELECTING_JAVA = "selecting_java"
    DOWNLOADING_JAVA = "downloading_java"
    INSTALLING_JAVA = "installing_java"
    DOWNLOADING_CLIENT = "downloading_client"
    DOWNLOADING_LIBRARIES = "downloading_libraries"
    DOWNLOADING_ASSET_INDEX = "downloading_asset_index"
    DOWNLOADING_ASSETS = "downloading_assets"
    CHECKING_MODS = "checking_mods"
    DOWNLOADING_MODS = "downloading_mods"
    DOWNLOADING_CONTENT = "downloading_content"
    CHECKING_MODPACK = "checking_modpack"
    DOWNLOADING_MODPACK = "downloading_modpack"
    DOWNLOADING_UPDATE = "downloading_update"
    BUILDING_CONTEXT = "building_context"
    BUILDING_COMMAND = "building_command"
    LAUNCHING = "launching"
    FINISHED = "finished"
